Tolerate missing containers when trying to clean up
Seen in the gate:

    Traceback (most recent call last):
      File "test/functional/tests.py", line 97, in setUpClass
        cls.env.setUp()
      File "test/functional/tests.py", line 2561, in setUp
        super(TestFileComparisonEnv, cls).setUp()
      File "test/functional/tests.py", line 81, in setUp
        cls.account.delete_containers()
      File "test/functional/swift_test_client.py", line 495, in delete_containers
        cont.update_metadata(hdrs={'x-versions-location': ''})
      File "test/functional/swift_test_client.py", line 558, in update_metadata
        self.conn.make_path(self.path))
    test.functional.swift_test_client.ResponseError: 404: 'Not Found'

Presumably, this was because the account-update to remove the container
from listings had to be handled async, so a deleted container still
showed up in listings.

We might still hit errors when we go to empty out the already-deleted
container, though :-/

Change-Id: I0671f65f5214337c07644cb0bb4a945c5857ab9d