py3: Make etag-quoter work
Previously, func tests (might?) complain like

   TypeError: 'dict_items' object does not support item assignment

Change-Id: Ic1a81f5b7262942ea52aa1de87cfcde25a2457ba