bufferedhttp: Tolerate socket being None
Seen in prod:

Traceback (most recent call last):
  File ".../swift/proxy/controllers/obj.py", line 416, in _get_conn_response
    self.app.node_timeout, not final_phase)
  File ".../swift/proxy/controllers/obj.py", line 1645, in await_response
    self.resp = self.conn.getexpect()
  File ".../swift/common/bufferedhttp.py", line 229, in getexpect
    response = BufferedHTTPResponse(self.sock, **kwargs)
  File ".../swift/common/bufferedhttp.py", line 64, in __init__
    self._real_socket = sock.fd._sock
AttributeError: 'NoneType' object has no attribute 'fd'

Change-Id: I35b3660f954bcf91aee2698b2c9cc10d5447abc1
Co-Authored-By: Clay Gerrard <clay.gerrard@gmail.com>