s3token: When caching is enabled, default auth_type to password
Otherwise, if you just set secret_cache_duration and skip configuring
auth_type, you get a not-very-obvious

    TypeError: sequence item 0: expected string, NoneType found

bubbling up from stevedore. Now, you'd get something like

    MissingRequiredOptions: Auth plugin requires parameters which were
    not given: auth_url

Change-Id: Ifddbb9df60207dfaaf0434877f4fe6af5c26bdf8