py3: Fix swift-recon
Avoid things like

    TypeError: '<' not supported between instances of 'NoneType' and 'int'

Change-Id: I82edbf1ddcc28f86e97405d21db0b96249412eac
(cherry picked from commit 2edcd0b7b9dd02a041fd1452ea17efda5f27f21c)