crypto: Fix listings when pipeline was misconfigured
We've seen reports of folks getting back 500s when trying to list
containers where some (but not all) objects have the wrong path in
their crypto meta due to pipeline misconfiguration.

The trouble comes down to how we cache container keys for the listing.
This has been present since encryption was written, and for good cause:
deriving a key is assumed to be non-trivial, so we don't want to go
doing it thousands of times for a listing when the result should always
be the same. We've updated how we do that caching twice: first when we
added support for multiple root secrets, and again to account for
different metadata versions.

However, we also need to cache by (container) path. Otherwise, the
first container encountered in the listing gets stuck and the next item
that uses a different container causes a traceback ending like

  File ".../middleware/crypto/decrypter.py", line 420, in process_json_resp
    new_body = json.dumps([self.decrypt_obj_dict(req, obj_dict)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../middleware/crypto/decrypter.py", line 438, in decrypt_obj_dict
    obj_dict['hash'] = self.decrypt_value(
                       ^^^^^^^^^^^^^^^^^^^
  File ".../middleware/crypto/decrypter.py", line 138, in decrypt_value
    return decoder(crypto_ctxt.update(base64.b64decode(value)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../middleware/crypto/decrypter.py", line 440, in <lambda>
    decoder=lambda x: x.decode('utf-8'))
                      ^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1:
invalid start byte

Related-Bug: #1729921
Related-Change: I1a6bcdebdb46ef03c342428aeed73ae76db29922
Related-Bug: #1813725
Change-Id: Ib43b5f3424002ec8b82af04ece6e585ae63207c2
Signed-off-by: Tim Burke <tim.burke@gmail.com>