Fixing target for cross-ref 'get_data_dir'
At the moment, the `get_data_dir` ref in [0] is not
pointing to anything. This patch amends that and
links it to (what I think) is the correct policy string.

Without updating this change, local tox builds
for swift documentation fail with the following
error: Warning, treated as error: /home/asettle/openstack/swift/doc
/source/overview_policies.rst:555:more than one target found for
cross-reference u'get_data_dir': swift.obj.reconstructor.get_data_dir,
swift.obj.diskfile.get_data_dir, swift.obj.replicator.get_data_dir

[0] https://docs.openstack.org/swift/rocky/overview_policies.html#object-server

Change-Id: I7c699e4fc46706a4971fce5a85ed335f471d3a2b
(cherry picked from commit f21f48b73c500022f5ea309fd0a0cd5196a51b9b)