sharder: Prevent ValueError when no cleaving contexts
Otherwise, we trip an error in logs:

   ValueError: max() arg is an empty sequence

Co-Authored-By: Matthew Oliver <matt@oliver.net.au>
Change-Id: I68f52f28edf9bdb9c534983cf353b72ecfaac426
(cherry picked from commit e53c82cd32e99513dba00a28c29953cadcc9bd87)