Make swift client easier to wrap
In the process of wrapping for profiling, a trivial wrap with def main()
ended in a ton of these:
    NameError: global name 'parser' is not defined

A closer investigation revealed an apparent confusion in argument names.
The problem was introduced by commit 985968f76550251904b64d12de025fa5d65ed03f
of November 2010. Note that Greg fixed st_delete() correctly in that one,
but apparently forgot the others.

Unit tests pass for both current (bad) code, and the patched code.
By the magic of Python scoping, current code works, just impossible
to wrap for a quick hack.

Change-Id: I18f2494ce2a201d04d49f99ea259d141939dcb6a